[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
soga-node-sale = "2VHjvzPThzEXeSMWgKTBtQM9LuB6Qh2a6E9XNJieajFG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/bilalafzal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./dep/metadata.so"

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "J83w4HKfqxwcq3BEMMkPFSppX3gqekLyLJBexebFVkix"

[[test.validator.clone]]
address = "5SSkXsEKQepHHAewytPVwdej4epN1nxgLVM84L4KXgy7"

[[test.validator.clone]]
address = "38xoQ4oeJCBrcVvca2cGk7iV1dAfrmTR1kmhSCJQ8Jto"
