[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
soga-node-sale = "4cQkDBqFZmuiuwsQnbrFEU5kcRUTCYS1agegC3yLVYQq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/bilalafzal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 5000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./dep/metadata.so"

[[test.genesis]]
address = "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ"
program = "./dep/pyth_receiver.so"

[[test.genesis]]
address = "pythWSnswVUd12oZpeFP8e9CVaEqJg25g1Vtc2biRsT"
program = "./dep/pyth_price_feed.so"

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

# SOL/USD Pyth Sponsored Feeds Address
[[test.validator.clone]]
address = "7UVimffxr9ow1uXYxsr4LHAcV58mLzhmwaeKvJ1pjLiE"

# USDT/USD Pyth Sponsored Feeds Address
[[test.validator.clone]]
address = "HT2PLQBcG5EiCcNSaMHAjSgd9F98ecpATbk4Sk5oYuM"

# USDC/USD Pyth Sponsored Feeds Address
[[test.validator.clone]]
address = "Dpw1EAVrSB1ibxiDQyTAW6Zip3J4Btk2x4SgApQCeFbX"
